version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm install
      - npm run build
      - mv dist/static/static/* dist/static
      - rm -r dist/static/static
artifacts:
  files:
    - "**/*"
