<template>
    <v-container fluid fill-height>
      <v-card>
        <v-card-header>
        <h1>ClimbAssist.com Terms of Use</h1>
        <h2>Community Guidelines</h2>
        </v-card-header>
        <v-card-text class="text-left">
          <h3>Acceptance</h3>
          <h4>1. BY USING OR VISITING CLIMBASSIST.COM AND ANY WEBPAGES GENERATED BY CLIMB ASSIST LLC, YOU AGREE TO THE FOLLOWING TERMS OF USE.</h4>
          <p>2. Use of Climb Assist.com (the “Site”) indicates that you have read and understood the Terms of Use (the “Terms”).</p>
          <p>3. Climb Assist LLC (the “Company”) reserves the right to modify these Terms at the Company’s discretion. The Company may provide notice of such modifications, but notice is not required in order to promptly make improvements to the website and such functionality from time to time at the Company’s discretion and in order to make the website more useful for you.</p>
          <p>4. Any notice of the modification may be provided through climbassist.com, email, or other manner of communication determined by the Company to be effective to provide such notice.</p>
          <p>5. You, the user, are encouraged to review these Terms on a regular basis and you agree to be bound by any such modifications.</p>
          <p>6. These Terms are by and between you and the Company and no third-party rights or benefits are intended, created, or conferred.</p>
          <h3>Service</h3>
          <p>1. The Site provides the opportunity for you to shop for, purchase, view, inspect, through such features as may be added from time to time, or otherwise interact with Climb Assist maps, merchandise, and tools.</p>
          <p>2. “Maps” include any two or three dimensional depiction of terrain provided by the Company, including such climbing paths or other data, explicit or meta, that informs the terrain, climb, or otherwise along with such pictures or images used to generate the two or three dimensional depiction of terrain and such written descriptions or other information related to the use of or commentary of the two or three dimensional depiction of terrain.</p>
          <p>3. “Products” include anything offered for sale, including but not limited to reproductions of a Map, merchandise, tools, or otherwise as determined by the Company from time to time.</p>
          <p>4. The Site may provide links to third-party websites for a variety of reasons, including to access the Company’s social media, payment processing, or other integration deemed necessary by the Company.</p>
          <p>5. Such third-party websites are not owned or controlled by the Company and Company expressly disclaims the content, opinions, policies, practices, and all other aspects of any linked third-party website.</p>
          <p>6. Such links are provided for your convenience and reference. The Company expressly states that the use of such third-party websites are governed by the third-party website and any legal agreements or otherwise provided by the third-party website.</p>
          <h3>Use of Maps</h3>
          <p>1. You are encouraged to review the various Climbing Areas for which Maps exist, including using the in browser tools to review the three dimensional images and such other features as may be included from time to time in the Maps.</p>
          <p>2. The Maps provided are for informational use only and climbing is inherently dangerous, each and every climber has the responsibility and duty to ensure their own safety while climbing and the Company makes no representations, warranties, or otherwise suggesting you should use the Maps in your climb.</p>
          <p>3. The review and use of these Maps is permitted only through climbassist.com or through any downloadable application created by the Company or downloadable from the website, any other use is not permitted.</p>
          <p>4. You shall not and shall not cause any data imbedded in, necessary for, or extrapolated from the Maps to be removed from the website, except to the degree such data exists in other forms prior to the creation of this website.</p>
          <h3>Purchases</h3>
          <p>1. You are encouraged to browse the Products and spend time on the Site.
          <p>2. If you decide to purchase one or more Products, you will be taken to a processing page.</p>
          <p>3. You will comply with the terms and conditions, including the privacy policy, of the credit card processing page (the “Processor”).</p>
          <p>4. The Site and the Company will not collect any information except name, address, and order for any purchase.</p>
          <p>5. Your information related to purchasing will be protected by the Processor and any claims related to unauthorized disclosure, theft, lack of protect, misuse or other data protection claim shall be directed to the Processor.</p>
          <p>6. In connection with your use of the Site, you agree to comply with all applicable laws.</p>
          <h2 class="text-center">Privacy</h2>
          <h3>Privacy Policy</h3>
          <p>1. This Privacy Policy outlines the nature, purpose, use and sharing of any Personally Identifiable Information (“PII”) collected via the Site, forum, or other data collection function. PII may include: your name, email, mailing and/or home address, phone numbers, or other information that identifies you personally.</p>
          <p>2. Any other data that is not statutorily PII may be protected to the extent PII is protected, however under no circumstances shall the definition of PII in these terms be read to be more expansive than provided by established law.</p>
          <p>3. Generally, PII is collected by voluntary submission by Member. By doing so, you are giving the Company permission to use the information for the purpose requested by the Company. Your decision not to provide certain information may result in the Company being unable to provide the service desired.</p>
          <p>4. If you voluntarily provide PII, through forms or email, the Company will use that information to help provide the information or service you have requested or to respond to you. The information we may receive varies based on what you do when visiting the Site.</p>
          <p>5. When PII is requested, the reasons for collecting it and a description of the intended use of the information may be provided.</p>
          <p>6. Should you provide your email address, the Company will provide you with newsletters and other information as it becomes available or based upon your subscription preferences for such mailings.</p>
          <p>7. Email is not necessarily secure and it is suggested you do not send sensitive personal data such as bank account, credit card information, or other similar data to the Company by email.</p>
          <p>8. The Company automatically collects information about each visit for website management and security purposes only. Such information helps update the website. Such information may include: (i) the internet domain from which you access the website, (ii) the internet protocol address from which you access the website, (iii) the type of browser used, (iv) the operating system used to access the website, (v) the date and time of access, (vi) the universal resource locator (“URL”) or address of the pages visited, (vii) log in information such as username, (viii) the URL of any forwarding site, (ix) additional location information and (x) such other information as is requested from time to time.</p>
          <p>9. The automatically collected information is provided for our web development team.</p>
          <p>10. Information that is not PII or PII stripped of identifying features may be provided to third parties to develop advertising or sponsorship relationships or other business development strategies.</p>
          <p>11. The use of social media websites and third-party websites by you or the Company must comply with the privacy policies of such social media websites and third- party websites. As such, more data may be collected based on plug-ins or application uses on the Company website of such social media websites and third-party websites.</p>
          <p>12. Any PII collected is secured to the best available standards behind protections such as firewalls, secure socket layer, encryption, password protections, and other reasonable precautions.</p>
          <p>13. Should the Company be hacked and your PII be stolen, the Company, pursuant to conscious and the requirements of law, will notify you as soon as possible.</p>
          <p>14. All information submitted to the Company shall be retained until (1) 2 years after an account has been closed or (2) for a period of time reasonable and in the discretion of the Company.</p>
          <h2 class="text-center">Cookies</h2>
          <p>To enrich and perfect your online experience, the Company uses “Cookies”, similar technologies and services provided by others to display personalized content, appropriate advertising and store your preferences on your computer.</p>
          <p>A cookie is a string of information that a website stores on a visitor’s computer, and that the visitor’s browser provides to the website each time the visitor returns. The Company uses cookies to help identify and track visitors, their usage of the Site, and their website access preferences. Visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using the Site, with the drawback that certain features of The Site may not function properly without the aid of cookies.</p>
          <p>By continuing to navigate our website without changing your cookie settings, you hereby acknowledge and agree to The Company’s use of cookies.</p>
          <h2 class="text-center">Accounts and Termination</h2>
          <h3>Creating or Reinstating an Account</h3>
          <p>1. You are encouraged to create an account, secured by email address and password, with the Site (the “Account”).</p>
          <p>2. To create an Account, you will submit a username, password, and such other information as requested by the Company and as you desire for any section that is not required.</p>
          <p>3. The Company may make recommendations about your username, password, and other sensitive details - in particular, suggestions on how to make a stronger or better username or password.</p>
          <p>4. You may elect to save and record payment information, on a third-party site, connected to the Account.</p>
          <p>5. There may be other disclosures you may be asked to make, such disclosures are to provide better service to you and are strictly voluntary.</p>
          <p>6. To the extent you have closed an Account, you may by registering an Account under the same email address, reinstate an Account.</p>
          <p>7. A new password will be requested for the Account to be reinstated.</p>
          <p>8. A reinstated Account will contain the information previously disclosed, including, to the degree permitted by the third-party processor, payment information.</p>
          <p>9. After two years, an Account may no longer be reinstated.</p>
          <h3>Closing your Account</h3>
          <p>1. You have the right to close your account at any time, by so electing while logged into your account.
          <p>2. Information provided through the privileges granted to the Account will remain on the Site unless and until there is a request to remove such information.
          <p>3. Any information protected under the Privacy Policy, the retention of the information is governed by the Privacy Policy.
          <p>4. Any other information obtained through the Account shall be kept for a period of two years or until the Account is reinstated.
          <h3>Privileges granted with an Account</h3>
          <p>1. In addition to the general uses of an Account, there are certain privileges granted with an Account when signed in.</p>
          <p>2. An Account has the privileges as advertised by the Company from time to time as provided to Members or indicated on the climbassist.com as members only, or with some other designation reasonably designed to indicate only Members have access to the feature(s).</p>
          <h3>Conduct</h3>
          <p>1. To the extent you can comment, you agree to keep such comments focused on the Maps or Products, or otherwise on topic in such forums as may be provided.</p>
          <p>2. Comments with inappropriate language - including but not limited to hate speech, swear or curse words, attacks on individuals, and other inappropriate language as determined at the discretion of the Company - shall be removed.</p>
          <p>3. You shall not act or comment in a toxic or harmful way to the community and inappropriate posts may trigger review of your account or continued access to the Site.</p>
          <p>4. To the extent your comments and other use of the privileges of an Account cause others to submit complaint(s) about your actions, the Company will take appropriate action, including reviews of those complaints.</p>
          <h3>Termination of Account</h3>
          <p>1. Should you violate any law in connection with the use of the Site, the Company reserves the right to terminate your Account.</p>
          <p>2. Should you violate any of the included Terms, specifically but not limited to the provisions on Conduct, the Company reserves the right to terminate your Account.</p>
          <p>3. Waiver by the Company of the right to terminate your Account for any instance is not a waiver of the right for all instances.</p>
          <p>4. If your account is terminated, it may not be reinstated.</p>
          <p>5. If your account is terminated, your information will be handled in accordance with the provisions under Closing your Account, except with regard to reinstatement.</p>

          <h2 class="text-center">User Create Content and Digital Millennium Copyright Act</h2>
          <h3>Copyright</h3>
          <p>1. The Maps or Products are fully owned by the Company. All rights reserved.
          <p>2. The three dimensional Maps, including the code and data necessary to generate the Maps, and photos of the Products are owned by the Company. All rights reserved.
          <p>3. You shall not copy, download, repost, or otherwise retransmit such Maps or images without express consent of the Company.
          <p>4. Should you copy, download, repost, or otherwise retransmit such images, you may be in violation of the Copyright Act, 17 U.S.C § 101 et. sec. and the Company may elect to pursue any and all legal remedies associated with the Copyright violation.
          <p>5. To the extent the Company creates any content, the Company affirmatively states that all rights are reserved.
          <p>6. To the extent the you create comments, art, or other copyrightable materials, the Company explicitly disclaims any right and ownership to such comments, art, or other copyrightable materials with the exception that the Company has and retains the right to remove such comments, art, or other copyrightable material if it does not comport with the Conduct provisions of these Terms.
          <p>7. To the extent you create comments or other copyrightable materials, the Company may post such comments or other copyrightable material to social media websites, blogs, or other marketing materials.
          <p>8. Prior to use of such comments or other copyrightable material, the Company may attempt to notify you through the provided email address, if you have an account.
          <p>9. To the extent your comments are helpful for business development, such comments may be used by the Company for such purposes as are claimed in these Terms.
          <h3>General</h3>
          <p>Age: You state that you are over the age of 13 in order to make an account and over the age of 18 and able to be legally bound by contract or are acting on behalf of someone younger, such as a child.</p>
          <p>Assignment: This Agreement cannot be assigned, except for any successors to the Company.</p>
          <p>Choice of Venue: To the extent litigation arises from these terms, you agree all such litigation will take place in the Federal District of Colorado or the State courts of Colorado located in Larimer County, Colorado.</p>
          <p>Choice of Law: These Terms shall be interpreted according to the laws of the State of Colorado and the laws of the United States of America.</p>
          <p>Full and Complete: These Terms are the full and complete understanding by and between you and the Company.</p>
          <p>Attorney’s fees: A prevailing party on any issue arising out of these Terms shall be entitled to Attorney’s Fees.</p>
          <p>Waiver: A waiver of any right or duty outlined in these Terms based upon circumstances is a waiver of an individual instance of such right or duty. Such a waiver is not a waiver for all time of the right or duty.</p>
          <p>Severability: Should any provision be found by any Court to be illegal or ineffective as a matter of law, such provision shall be struck immediately and be given no weight or effect.</p>
        </v-card-text>
      </v-card>
    </v-container>
</template>

<script>
export default {
  name: 'terms-and-conditions',
  data: () => ({}),
  props: {},
  methods: {}
}
</script>
